language: python
# python version
python:
  - "3.6.0"
# command to install dependencies
install:
  - pip install -r requirements.txt 
# command to run tests
script: 
  - nosetests -v --with-coverage
  - coverage
  - coveralls
 
after_success:
  - coveralls  