language: python

services:
  - postgresql

# python version
python:
  - "3.6.0"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - export SECRET_KEY="7pgozr2jn7zs_o%i8id6=rddie!*0f0qy3$oy$(8231i^4*@u3"

before_script:
  - psql -c 'create database test_db;' -U postgres

# command to run tests
script:
  - python manage.py test
  - coverage
  - coveralls

after_success:
  - coveralls
