# Generated by Django 2.1.4 on 2019-01-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.BooleanField(default=False),
        ),
    ]
