# Generated by Django 2.1.5 on 2019-01-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follows',
            new_name='following',
        ),
    ]
