# Generated by Django 2.1.4 on 2019-01-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190116_0739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favorited',
        ),
        migrations.RemoveField(
            model_name='article',
            name='favoritesCount',
        ),
    ]
