# Generated by Django 2.1.5 on 2019-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20190130_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tagList',
            field=models.ManyToManyField(default=[], to='articles.Tag'),
        ),
    ]
