# Generated by Django 2.1.5 on 2019-01-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_likearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='likearticle',
            name='modified_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='likearticle',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
