# Generated by Django 2.1.4 on 2019-01-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_tag_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50)),
        ),
    ]
