# Generated by Django 2.1.4 on 2019-01-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tagList',
        ),
    ]
