# Generated by Django 2.1.4 on 2019-01-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_taglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
