# Generated by Django 2.1.5 on 2019-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190118_1139'),
        ('articles', '0008_delete_tag'),
    ]

    operations = [
    ]
