# Generated by Django 2.1.5 on 2019-01-21 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_merge_20190121_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likearticle',
            old_name='article_id',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='likearticle',
            old_name='user_id',
            new_name='user',
        ),
    ]
