# Generated by Django 2.0.10 on 2019-02-05 05:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(choices=[
                 (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('article', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('rater', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
    ]
