# Generated by Django 2.1.5 on 2019-01-23 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20190121_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='points',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
